### ISSUE TITLE
Add Gradle support

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster-micronaut#14]

**Comment by atomfrede** [comment]
I can have a look at this. Most likely after I the edge cases in the neo4j integration have been fixed

**Comment by sendilkumarn** [comment]
Cool that will be awesome.

**Comment by willbuck** [comment]
@atomfrede are you actively work on this? I had started on it yesterday afternoon, but can pick up something else if you're already into it

**Comment by atomfrede** [comment]
No I didn't start yet. So go ahead!

**Comment by willbuck** [comment]
Okay cool. I'm starting w/ a branch of the sample-app that removes all the maven bits and adds the gradle bits, so it might be a little bit yet before I branch the generator. I'll link the sample app branch once I have it working (was a little stuck this morning but had @ZacharyKlein and @jameskleeh work through some micronaut-data related kinks this afternoon with me!)

**Comment by willbuck** [comment]
Okay, [gradle branch is working](https://github.com/jhipster/jhipster-sample-app-micronaut/tree/gradle)

More needed to change than expected; we had some things working out of happenstance by the look of things in the maven sample app. For example, we were previously including some spring things [via the micronaut-hibernate-jpa](https://github.com/jhipster/jhipster-sample-app-micronaut/commit/b437e88178889a0fc2d08a8aaccb478ca1554f90#diff-c197962302397baf3a4cc36463dce5eaR236), and importing those [annotations instead of the micronaut data ones](https://github.com/jhipster/jhipster-sample-app-micronaut/commit/b437e88178889a0fc2d08a8aaccb478ca1554f90#diff-8e195fc30f7efec1b1b72fccdbeee525) module in `io.micronaut.configuration`, which we shouldn't be using in conjunction with micronaut-data's hibernate-jpa module.

Thus, the PR for this issue will likely be changing some of the Maven stuff as well. I can split into two PRs for sake of clarity, @atomfrede @sendilkumarn @jdubois do y'all think that'd be preferable (have the maven output match the necessary code changes first, then add the gradle support?)
