### ISSUE TITLE
Repository should only use 'save' method

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster-micronaut#175]
##### **Overview of the feature request**
I'm not sure if this is a bug or a feature request, so I'm leaving it as FR.

I think using `mergeAndSave`method in repositories should be avoided.

##### **Motivation for or Use Case**

According to the [documentation](https://micronaut-projects.github.io/micronaut-data/1.0.2/guide/index.html#_updating_an_instance_update), in order to either create or update an entity, the method `save` should be used.

##### **Related issues or PR**
None that I know of.

**Comment by murdos** [comment]
When no service is generated for entity, I'm not sure because of the `@Transactional` annotation on the `mergeAndSave` method.
But when entity is generated with serviceClass or serviceImpl we should definitely not generate and use this `mergeAndSave`: the transaction is handled at the service level.
